const LOGIN_MODAL_TITLE = "Sign in";
const LOGIN_MODAL_BUTTON_TEXT = "Sign in";
const LOGIN_MODAL_ALTERNATE_BUTTON_TEXT = "Sign up";
const LOGIN_MODAL_EMAIL_INPUT_LABEL_TEXT = "Email";
const LOGIN_MODAL_EMAIL_INPUT_PLACEHOLDER_TEXT = "Enter email";
const LOGIN_MODAL_PASSWORD_INPUT_LABEL_TEXT = "Password";
const LOGIN_MODAL_PASSWORD_INPUT_PLACEHOLDER_TEXT = "Enter password";
const REGISTER_MODAL_TITLE = "Sign up";
const REGISTER_MODAL_BUTTON_TEXT = "Sign up";
const REGISTER_MODAL_ALTERNATE_BUTTON_TEXT = "Sign in";
const REGISTER_MODAL_EMAIL_INPUT_LABEL_TEXT = "Email";
const REGISTER_MODAL_EMAIL_INPUT_PLACEHOLDER_TEXT = "Enter email";
const REGISTER_MODAL_PASSWORD_INPUT_LABEL_TEXT = "Password";
const REGISTER_MODAL_PASSWORD_INPUT_PLACEHOLDER_TEXT = "Enter password";
const REGISTER_MODAL_USERNAME_INPUT_LABEL_TEXT = "Username";
const REGISTER_MODAL_USERNAME_INPUT_PLACEHOLDER_TEXT = "Enter your username";

export {
  LOGIN_MODAL_TITLE,
  LOGIN_MODAL_BUTTON_TEXT,
  LOGIN_MODAL_ALTERNATE_BUTTON_TEXT,
  LOGIN_MODAL_EMAIL_INPUT_LABEL_TEXT,
  LOGIN_MODAL_EMAIL_INPUT_PLACEHOLDER_TEXT,
  LOGIN_MODAL_PASSWORD_INPUT_LABEL_TEXT,
  LOGIN_MODAL_PASSWORD_INPUT_PLACEHOLDER_TEXT,
  REGISTER_MODAL_TITLE,
  REGISTER_MODAL_BUTTON_TEXT,
  REGISTER_MODAL_ALTERNATE_BUTTON_TEXT,
  REGISTER_MODAL_EMAIL_INPUT_LABEL_TEXT,
  REGISTER_MODAL_EMAIL_INPUT_PLACEHOLDER_TEXT,
  REGISTER_MODAL_PASSWORD_INPUT_LABEL_TEXT,
  REGISTER_MODAL_PASSWORD_INPUT_PLACEHOLDER_TEXT,
  REGISTER_MODAL_USERNAME_INPUT_LABEL_TEXT,
  REGISTER_MODAL_USERNAME_INPUT_PLACEHOLDER_TEXT,
};
